export const enum EIcons {
  Dashboard = "unjs:theme-colors",
  User = "mdi:user",
  Home = "mdi-light:format-indent-increase",
  MenuOpen = "mdi-light:format-indent-decrease",
  MenuClose = "mdi-light:format-indent-increase",
  Fullscreen = "akar-icons:full-screen",
  Locale = "mdi:language",
  Theme = "icon-park-outline:theme",
  Close = "akar-icons:x-small",
  Vue = "mingcute:vue-line",
  React = "uil:react",
  ReactTest = "file-icons:test-react",
  Form = "mdi:form-outline",
  Code = "mingcute:code-line",
}
