/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    TemplifyForm: typeof import('./src/components/TemplifyForm.vue')['default']
  }
}
